### ISSUE TITLE
[Bug]: application just quit on click

### ISSUE THREAD

**Issue by neoedmund** [bottlesdevs/Bottles#1756]
### Describe the bug

application just quit on click left menus like 'Programs' 'Dependencies'

### To Reproduce

` flatpak run 	com.usebottles.bottles`
select a bottle
click 'Programs'

### Package

Flatpak from Flathub

### Distribution

Debian 11

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.8-gs
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 67494129664
    Free: 67493994496
RAM:
    MemTotal: 125.7GiB
    MemAvailable: 117.2GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

there are lots line of messages, but not direct causing quit
```
(bottles:2): GLib-GIO-CRITICAL **: 13:17:29.176: g_dbus_connection_emit_signal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

**Comment by mirkobrombin** [comment]
Distro?
Desktop?

**Comment by mirkobrombin** [comment]
Should be the same problem I was investigating some days ago and which I have already fixed. Wait for 2022.7.14 release pleas.

**Comment by Anachron** [comment]
@mirkobrombin is the flatpak updated automatically or do we need for someone to do it manually?

I'm asking because the current flatpak version is still `2022.6.28-brescia`.

**Comment by Anachron** [comment]
Shouldn't https://github.com/flathub/com.usebottles.bottles/blob/master/com.usebottles.bottles.yml#L360 show `2022.7.14`, not `2022.6.28`?

**Comment by neoedmund** [comment]
Hi, I upgrade to '2022.7.14-brescia-3' , but nothing changed, it quit without any related error message.

**Comment by Anachron** [comment]
I sometimes still have this issue, but it's better now.

Do you have dbus running? Do you get the same errors as before?

**Comment by neoedmund** [comment]
I use to run bottles without problem on the system.
dbus is running but maybe problem for some usage
`ps | grep dbus`

```
message+    dbus-daemon --system
user        dbus-launch --autolaunch 'someid' --binary-syntax --close-stderr
user        /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
user          /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
```
