### ISSUE TITLE
[Bug]: Can't launch Overwatch (No compatible grafics hardware was found. OxE00701B0)

### ISSUE THREAD

**Issue by KiritoStorm** [bottlesdevs/Bottles#2216]
### Describe the bug

When launching Overwatch with the Battle.net launcher this error message is displayed.

![image](https://user-images.githubusercontent.com/46503102/198720438-892482d8-4226-447c-8bd2-cb3b5afe0977.png)

### To Reproduce

1. Download the Battle.net Setup exe
2. Create a Gaming bottle
3. Launch the Battle.net exe with bottles
4. Install Overwatch
5. Start the game

### Package

Flatpak from Flathub

### Distribution

Zorin OS 16.2

### Troubleshooting Logs

```shell
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-52-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8347447296
    Free: 8347291648
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "9,2\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I already experienced this issue a few version before but was fixed the next day. (before OW2 Release)
Since the last updates, in the time where Overwatch 2 was released (04.10.22) there were some issue with Battle.net that seems to be fixed now.

I don't use the predefined installer, because of the night-light mode issues on Zorin #1662, but I can try that if needed, I just need to get some space on my disk.

**Comment by michaelwhitford** [comment]
I am having the same issue but with World of Warcraft today.  I run Linux Mint and there were updates to the nvidia driver.   Now I see this trying to launch a bottle that worked yesterday.
![bottles_nvidia_515_issue](https://user-images.githubusercontent.com/17480072/198815372-dfde04e2-649e-4373-a7a0-5f405e8efda6.png)

**Comment by michaelwhitford** [comment]
I was able to resolve my problem by having flatpak update runtimes.  It seems the newer nvidia 515 driver from Ubuntu needed a corresponding flatpak install.

I fixed it with `flatpak update`

This installed:
org.freedesktop.Platform.GL.nvidia-515-65-01
org.freedesktop.Platform.GL32.nvidia-515-65-01

**Comment by GlitchWitch** [comment]
I'm running into the same issue as @KiritoStorm with the same environment variables for an egpu.

Checking `nvidia-smi` shows that the discrete GPU is not being used which is likely to root cause of this error.

Without those environment variables, and with the discrete GPU toggle disabled, the game will launch but only utilise the integrated Intel GPU.

`flatpak update` had no effect, manually upgrading the driver package in apt and ensuring a matching install in flatpak also did not work.

**Comment by KiritoStorm** [comment]
Thank you for joining the conversation.

I tried to upgrade the dependencies with flatpack and apt but it hasn't worked, also the latest installer for my grafic card from nvidia run into an error. 

`nvidia-smi` now shows the version of the 515 instead of 510 after a restart.
`NVIDIA-SMI 515.65.07    Driver Version: 515.65.07    CUDA Version: 11.7`

But that the error still persists and maybe I broke some stuff, because I wasn't able to normally upgrade the nvidia driver package, because the system [was holding back](https://itsfoss.com/following-packages-have-been-kept-back/) for some reason.

**Comment by KiritoStorm** [comment]
@GlitchWitch How do you see with `nvidia-smi` if the GPU is used or not? I think I have disabled the CPU graphics so it should work I guess, it also works on windows.

**Comment by cyberphantom52** [comment]
Please post a screenshot of the components page.

**Comment by GlitchWitch** [comment]
@cyberphantom52 Do you mean the "DLL Components" settings page or the "Runner Components" section of the bottle preferences? Since they seem to be the same information I've included the later.

![image](https://user-images.githubusercontent.com/32590246/198882294-dcd05929-d247-402c-8ef0-a926dc86ac03.png)

Also here is my debug info...

```
Version: 2022.10.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.17.0-1020-oem
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 16680173568
    Free: 16680017920
RAM:
    MemTotal: "33.4\_GB"
    MemAvailable: "31.1\_GB"
Bottles_envs: null
```

@KiritoStorm Anything using the GPU should appear under the bottom "Processes" section like so...
| GPU not in use | GPU in use by glxgears via prime-run |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/32590246/198882379-446cc23e-98dc-4d60-81d6-4961b71f956e.png) | ![image](https://user-images.githubusercontent.com/32590246/198882407-6657bab2-a7b3-4907-9874-ac1e5c2d25c0.png) |
