### ISSUE TITLE
[BUG] Deleting a bottle "breaks" the GUI

### ISSUE THREAD

**Issue by guihkx** [bottlesdevs/Bottles#224]
**Describe the bug**
If you have two or more Bottles and you delete one, you won't be able to configure the other ones, unless you restart the app.

**Installation**
 - Method: Flatpak
 - Version: 3.1.4

**To Reproduce**

1. Launch Bottles using the terminal so you can see the errors.
2. Create two bottles.
3. Delete the first one.
4. Try to change settings of the second bottle.
5. This message will show up in the console:

    ````bash
    Traceback (most recent call last):
      File "/app/share/bottles/bottles/pages/list.py", line 180, in show_details
        self.window.show_details_view(configuration=self.configuration)
      File "/app/share/bottles/bottles/window.py", line 237, in show_details_view
        self.page_details.set_configuration(configuration)
      File "/app/share/bottles/bottles/pages/details.py", line 595, in set_configuration
        self.switch_dxvk.handler_block_by_func(self.toggle_dxvk)
    TypeError: nothing connected to <bound method BottlesDetails.toggle_dxvk of <details.BottlesDetails object at 0x7fa77e865ec0 (BottlesDetails at 0x55918ff6b3e0)>>
    ````

6. Only restarting the app fixes, as far as I could tell.

**Expected behavior**
Deleting a bottle shouldn't "break" the GUI.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: rolling release

**Additional context**
N/A

**Comment by mirkobrombin** [comment]
Something must have broken with a recent update because I have never encountered this problem. I will investigate

**Comment by mirkobrombin** [comment]
It should be fixed with the latest build

**Comment by guihkx** [comment]
The original error is gone, but the UI still breaks and a different error is shown:

```
Traceback (most recent call last):
  File "/tmp/.mount_Bottle4NT11Y///usr/local/share/bottles/bottles/pages/list.py", line 184, in show_details
    self.window.page_details.update_combo_components()
  File "/tmp/.mount_Bottle4NT11Y///usr/local/share/bottles/bottles/pages/details.py", line 612, in update_combo_components
    self.combo_runner.handler_block_by_func(self.set_runner)
TypeError: nothing connected to <bound method BottlesDetails.set_runner of <details.BottlesDetails object at 0x7f187dc3ad00 (BottlesDetails at 0x28a1390)>>
```

Video:

https://streamable.com/8k0i6t

Tested with the latest unstable AppImage build.

**Comment by mirkobrombin** [comment]
Perhaps the configuration of one of the bottles is broken. Can you try to provide the config.json of your bottles or try to delete them manually?

**Comment by guihkx** [comment]
Sorry, I don't quite understand your question. If you watch the video I linked, you'll see that I created two new bottles. After that, I deleted the first one and then the UI broke, so I couldn't delete the second one (also the UI was still showing the first bottle I had just deleted).

**Comment by mirkobrombin** [comment]
I should have figured out what is causing the problem. I'll make a fix as soon as possible

**Comment by mirkobrombin** [comment]
I just pushed a fix that should fix the problem. Can you try the latest unstable build?

**Comment by guihkx** [comment]
It's fixed! Thank you very much :)
