### ISSUE TITLE
[Bug]: Failing to create new bottle

### ISSUE THREAD

**Issue by roworu** [bottlesdevs/Bottles#3137]
### Describe the bug

When I click "Create new bottle" button, it stuck on "creating Bottle" message for infinite.

### To Reproduce

1) Click create new bottle
2) Leave everything as by default and type some random name
3) Click "Create"
4) "Creating Bottle" message stuck forever...

### Package

Flatpak from Flathub

### Distribution

Fedora 39

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: gnome-xorg
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.7-200.fc38.x86_64
Disk:
    Total: 16777895936
    Free: 16777728000
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 23.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
roworu@fedora:~$ flatpak run com.usebottles.bottles
19:41:08 (INFO) Bottles Started! 
19:41:09 (INFO) Performing Bottles checks… 
19:41:09 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.10
 
19:41:09 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.4
 
19:41:09 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
19:41:09 (INFO) Runners found:
	 - soda-7.0-9
	 - sys-wine-8.0.2
 
19:41:09 (INFO) Catalog installers loaded 
19:41:09 (INFO) Catalog dependencies loaded 
19:41:09 (INFO) Catalog components loaded 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/new.py", line 190, in create_bottle
    dxvk=self.manager.dxvk_available[0],
IndexError: list index out of range

```
```


### Additional context

_No response_

**Comment by zUltimaPG3D** [comment]
in preferences, download dxvk, it should fix it

**Comment by zUltimaPG3D** [comment]
in more detail, open Preferences (should be Ctrl+, by default), go in the DLL Components tab and install the latest dxvk (or whatever version you want)

**Comment by resiehnnes** [comment]
@zUltimaPG3D , thanks, that fixed my issue

**Comment by buck2825** [comment]
Bug still present, Bottles 51.13 installed by flatpak on Manjaro

**Comment by Levan7** [comment]
Sill an issue on ubuntu

**Comment by jury68000** [comment]
> in more detail, open Preferences (should be Ctrl+, by default), go in the DLL Components tab and install the latest dxvk (or whatever version you want)

How to install dxvk in this Preferences/DLL Componets tab?
As in this tab, all I see is 4 black labels (one of them is "DXVK") but there is nothing else there, it looks kinda empty. I can not clikck on those labels or do anything. I guess I need some dependency or something is missing, but what?
